namespace FlashMapper;

/// <summary>
/// Static API for mapping operations. All functionality is generated by the Source Generator.
/// </summary>
/// <remarks>
/// FlashMapper uses specific methods instead of generics for maximum performance.
/// Example: var dto = Mapper.Map(user); // Returns UserDto automatically
/// This approach eliminates all generic overhead and provides compile-time type safety.
/// 
/// Configuration is done in methods marked with [MapperConfiguration]:
/// <code>
/// [MapperConfiguration]
/// public static void Configure()
/// {
///     Mapper.CreateMap&lt;User, UserDto&gt;();
/// }
/// </code>
/// 
/// The Source Generator analyzes these calls and generates specific Map() methods.
/// </remarks>
internal static partial class Mapper
{
    // All methods (CreateMap, Map, etc.) are generated by the Source Generator at compile-time.
    // This partial class exists to allow the generator to extend it.
}
