name: Feature Request
description: Suggest a new feature for VelocityMapper
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to map... but currently...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        Mapper.CreateMap<Source, Dest>()
            .WithCustomFeature(...)
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I've tried... but...
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
  
  - type: checkboxes
    id: performance
    attributes:
      label: Performance Impact
      description: Does this feature affect performance?
      options:
        - label: This feature may impact performance
        - label: Performance is not a concern for this feature
        - label: This feature improves performance
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature
    validations:
      required: false

